plugins {
    id 'com.android.application'
}

android {
    namespace 'kernel.unisocsu.kosherlauncher'
    compileSdk 35

    defaultConfig {
        applicationId 'kernel.unisocsu.kosherlauncher'
        minSdk 19
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    signingConfigs {
        release {
            storeFile file("../kosherlauncher-release.jks")
            storePassword "12345678"
            keyAlias "kosherlauncher"
            keyPassword "12345678"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
}